### ISSUE TITLE
Better documentation?

### ISSUE THREAD

**Issue by zlk89** [terence410/ts-datastore-orm#7]
I found this library really cool, but it is lacking of API documentation, and hard to know the purpose of each API, e.g., the meaning of `generateId`, `_id`.

**Comment by terence410** [comment]
Hi, 

I used this library for many of my internal project, I am pretty confident on the quality.

Speaking of doc, frankly, I am a bit too lazy. But you may try to read the test cases in https://github.com/terence410/ts-datastore-orm/tree/master/tests

Or which part you don't really get it. feel free to ask me, I will try to explain it more to you.

Regarding on the generateId, datastore has it's own id generate algorithm. If you set generateId to true. when you insert an entity without an _id, it will auto generate one after you inserted. Otherwise, you will get an error saying you didn't have _id provided.
